config/routes.rb
Rails.application.routes.draw do
  resources :twerps

  resources :sessions

  resources :users

  get 'logout', to: 'sessions#destroy', as: 'logout'

  root to: "users#new"

end

app/models/twerp.rb
class Twerp < ActiveRecord::Base

default_scope { order('created_at DESC') }

belongs_to :user

validate :content, length: { maximum: 140 }


end

app/models/user.rb
require 'digest/md5'
require 'bcrypt'

class User < ActiveRecord::Base
	attr_accessible :avatar_url, :bio, :email, :name, :password, :password_confirmation, :username
	
	has_secure_password

	has_many :twerps

	before_validation :prep_email
	before_save :create_avatar_url

	validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
	validates :username, presence: true, uniqueness: true
	validates :name, presence: true


	private

	def prep_email
		self.email = self.email.strip.downcase if self.email
	end

	def create_avatar_url
		self.avatar_url = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=50"
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	user = User.find_by_username params[:username]
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged In!"
    else
      flash[:error] = "Wrong username or password."
      redirect_to root_url
    end
  end

  def destroy
  	session[:user_id] = nil
    redirect_to root_url, notice: "Logged Out."
  end
end

app/controllers/twerps_controller.rb
class TwerpsController < ApplicationController

	def create
		twerp = Twerp.new(params[:twerp])
		twerp.user_id = current_user.id
	

		flash[:error] = "Your Twerp was over 140 characters" unless twerp.save
		redirect_to root_url

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
@user = User.new
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			session[:user_id] = @user.id
			redirect_to @user, notice: "Thank you for signing up for Twerpper"
		else
			render 'new'
		end

	end

	def show
		@user = User.find(params[:id])
		@twerp = Twerp.new
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/twerps_helper.rb
module TwerpsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twerpper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
    <div class="wrapper">
      <span>Twitter Clone</span>

      <% if current_user %>
        <%= link_to "Log Out", logout_path %>

      <% else %>
      <%= form_tag sessions_path do %>
        <%= text_field_tag :username, nil, placeholder: "username" %>
          <%= password_field_tag :password, nil,  placeholder: "password" %>
          <%= submit_tag "Log In" %>
      <% end %>
      <% end %>

      </div>
    </header>

	<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Twerpper</a>
    <ul class="nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Profile</a></li>
      <li><a href="#">Help</a></li>
    </ul>
  </div>
</div>

<div id="content">
    <div class="wrapper">
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: "flash #{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </div>


      



<footer>
<div class="wrapper">
  Twerpper - A Twitter Clone 
</div>
</footer>

</body>
</html>

app/views/twerps/_new_form.html.erb
<div class="panel right">
	<h1> Create A Twerp </h1>
	<%= form_for @twerp do |f| %>
		<%= f.text_area :content, class: "twerpText", id: "twerpText" %>
		<%= f.submit "Twerp!" %>
		<span id="charCount">0</span>
	<% end %>
</div>

app/views/users/new.html.erb
<div class="panel right">
	<h1> New to Twerpper? </h1>
	<p>
			<%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <ul>
          <% @user.errors.full_messages.each do |e| %>
            <li><%= e %></li>
          <% end %>
        </ul>
      <% end %>

      <%= f.text_field :email, placeholder: "email" %>
      <%= f.text_field :username, placeholder: "username" %>
      <%= f.text_field :name, placeholder: "name" %>
      <%= f.password_field :password, placeholder: "password" %>
      <%= f.password_field :password_confirmation, placeholder: "password" %>
      <%= f.submit "Create account" %>
    <% end %>

		</p>
	</div>

app/views/users/show.html.erb
<% if current_user %>
	<%= render 'twerps/new_form' %>
<% end %>


<div id="twerps" class="panel left">
	<h1> Your Twerpper Profile </h1>
	<div class="twerpWrapper">
		<img class="avatar" src="<%= @user.avatar_url %>"/>
		<span class="name"><%= @user.name %></span> @<%= @user.username %>
		
        <p>
        <%= @user.twerps.length %> Twerps
        <span class="spacing">XX Followers</span>
        <span class="spacing">XX Following</span>
        </p>
    </div>
</div>
<div class="panel left">
	<h1> Twerps </h1>
	<div class="twerpWrapper">
		Twerps coming...
	</div>
</div>